#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Screens
hdmi=`xrandr | grep ' connected' | grep 'HDMI' | awk '{print $1}'`

if [ "$hdmi" = "HDMI-1" ]; then
  xrandr --output LVDS-1 --off --output VGA-1 --off --output HDMI-1 --primary --mode 1360x768 --pos 0x0 --rotate normal --output DP-1 --off &
else
  xrandr --output LVDS-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output VGA-1 --off --output HDMI-1 --off --output DP-1 --off &
fi

# teclado en español
setxkbmap es &
# Wallpaper
feh --bg-scale Imágenes/wallpaper.jpg &
# Administrador de energia
xfce4-power-manager &
# systray battery icon
cbatticon &
# systray volume
volumeicon &
# Composer
picom &
# Network
nm-applet &
# Automount Devices
udiskie -t &
# Java Fonts
xsettingsd &